version: "3"
services:
  app:
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    # command: sh -c "./wait-for db:5432 -- echo ready"
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
