version: "3.7"
services:
  app:
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    command: sh -c "./wait-for db:5432 -t 10 -- echo $PGHOST && npm run create_db && npm run migrate up && npm start"
  db:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
